# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" --name browser-container --platform=linux/amd64 selenium/standalone-chrome:latest
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
  env:
    TEST_BROWSER: chrome
  continueOnError: true
- script: docker stop browser-container
- script: docker rm browser-container
