package test.ui;

import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.*;

/*
 * This class has been generated by Selenium IDE after recording the login scenario on localhost for Swag Labs application.
 * The purpose is to show how to write a basic Selenium test case
 * The recording was exported as Java Selenium with JUnit, with the only changes:
 * 1. setting the package to test.ui
 * Adding in the setup the setting of the property "webdriver.chrome.driver" pointing to the absolute folder on my computer of the Chrome Web Driver.
 * So this has to be changed accordingly
 */
public class LoginSeleniumIDETest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@BeforeTest
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "/Users/leonardolanni/Downloads/chromedriver_113_m1");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

	}

	@AfterTest
	public void tearDown() {
		driver.quit();
	}

	@Test(groups = { "old" })
	public void login() {
		System.out.println("vars os empty: " + vars.isEmpty());
		driver.get("http://localhost:3000/");
		driver.manage().window().setSize(new Dimension(1350, 637));
		driver.findElement(By.id("login_credentials")).click();
		driver.findElement(By.id("login_credentials")).click();
		{
			WebElement element = driver.findElement(By.id("login_credentials"));
			Actions builder = new Actions(driver);
			builder.doubleClick(element).perform();
		}
		driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
		driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
		driver.findElement(By.cssSelector(".login_password")).click();
		driver.findElement(By.cssSelector(".login_password")).click();
		{
			WebElement element = driver.findElement(By.cssSelector(".login_password"));
			Actions builder = new Actions(driver);
			builder.doubleClick(element).perform();
		}
		driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
		driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
		driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();

		System.out.println("D3. Test 4 End");
	}
}
